language: node_js
node_js:
- '6'
- node
- iojs
matrix:
  allow_failures:
  - node
  - iojs
install:
- npm install
- npm update
script:
- npm run build
- npm run test
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - antoine.plaskowski@epitech.eu
    on_success: change
    on_failure: always
  slack:
    secure: e5kezDK1RNo1ak0pUv0Sb5UTOrEFdLex1lc5HBAVAiMWwgML3DSFOtGy92QJf2omIEluwV9SirhCK5mAS2BNTDXca6SEekYSsiw+K1T5XDjNUopP8fbx0RVLz3OrksqW0Ss4ReIUvCANu3D9Bzp6fidy6AL03259apE+ghk4FIsEeYqxY/1YyyNGxuZTD0X0z+ppek+BAduel7Od1M4KIbNZcyfnQ3k8JWms5RAKYcpMPwj0sQNKiQlZfiGZcpa3MnHJFcsalJ9Ff5/5GbMxViPHa17GgyZQcBRbXc5qi7tekthu7lz6IwTonyUgsF4ihDZFF403yL/nBNkujrTL4dbRwBk6Pe9FS4TXCytWeg5H5mkzULOkMzHozPa0pnxpAVtEXt8kBUePsdpM8EXuRvbKDp6N7L3oiG9ahKkYS2+3lKIIxvf/fuxFmQQr6yGpXptYgqnSZyhYCCfUiENVcNdnitYiL9xUNtP/QsdAr0b80GXK4AGjXJHs+bjLtmK4JVqarox0Th1nIK8pAXGSYKgyz5SVNkUYf11dZjUPWJuXSlTqrzBhDKE+Snw3pJ56Bm0/5x43spesta2PdBYA/hCRDBmj0G8481qIsRgFaZsEY7JV/thlIGrUbXLlWaEZ9rbTkCWpFAgvWHq/QgVwQ0sxPdXeBzsaa0HjoRUkDHw=
