language: node_js
node_js:
- "6"
- "node"
- "iojs"
matrix:
  allow_failures:
  - "node"
  - "iojs"
install:
- npm install
- npm update
script:
- npm run build
- npm run test
cache:
  directories:
  - node_modules
